### ISSUE TITLE
Using gosling.js in Codesandbox results in TypeError (reading 'registerSerializer' from undefined)

### ISSUE THREAD

**Issue by puehringer** [gosling-lang/gosling.js#727]
Codesandbox is a popular way of sharing prototypes, so gosling.js should be compatible in my opinion. After following the [tutorial](http://gosling-lang.org/docs/#use-goslingjs-with-react), I set up [this codesandbox](https://codesandbox.io/s/gosling-js-pz7h7h?file=/package.json) and get the following error: 

```
index.js:27 TypeError: Cannot read properties of undefined (reading 'registerSerializer')
    at $csb$eval (index.mjs:8:49)
    at H (eval.js:31:28)
    at K.evaluate (transpiled-module.js:713:29)
    at ge.evaluateTranspiledModule (manager.js:340:33)
    at c (transpiled-module.js:695:31)
    at $csb$eval (gosling.es.js:100:21)
    at H (eval.js:31:28)
    at K.evaluate (transpiled-module.js:713:29)
    at ge.evaluateTranspiledModule (manager.js:340:33)
    at c (transpiled-module.js:695:31)
    at $csb$eval (App.tsx? [sm]:2:1)
    at H (eval.js:31:28)
    at K.evaluate (transpiled-module.js:713:29)
    at ge.evaluateTranspiledModule (manager.js:340:33)
    at c (transpiled-module.js:695:31)
    at $csb$eval (index.tsx? [sm]:3:1)
    at H (eval.js:31:28)
    at K.evaluate (transpiled-module.js:713:29)
    at ge.evaluateTranspiledModule (manager.js:340:33)
    at ge.evaluateModule (manager.js:311:34)
    at compile.ts:765:31
    at c (runtime.js:45:40)
    at Generator._invoke (runtime.js:274:22)
    at forEach.t.<computed> [as next] (runtime.js:97:21)
    at r (asyncToGenerator.js:3:20)
    at u (asyncToGenerator.js:25:9)
```

**Comment by sehilyi** [comment]
Thanks for reaching out! I agree that we should support Codesandbox.

This may be related to workers (threads) we use for BAM and VCF files:

- https://github.com/openlayers/openlayers/issues/13046
- https://github.com/codesandbox/codesandbox-client/issues/6313

**Comment by sehilyi** [comment]
As part of the post-v1 release, we are cleaning up GitHub issues. Feel free to open this again if anyone finds this relevant!
