### ISSUE TITLE
`TypeError: Cannot read private member #firstDraw`

### ISSUE THREAD

**Issue by sehilyi** [gosling-lang/gosling.js#950]
![Screenshot 2023-07-25 at 09 58 24](https://github.com/gosling-lang/gosling.js/assets/9922882/e1b31fe8-cdea-43c9-a876-f6311131f2e3)

![Screenshot 2023-07-25 at 09 56 49](https://github.com/gosling-lang/gosling.js/assets/9922882/a841ad82-7aa5-421f-85af-387139295aee)

Minimal reproducible spec:
```ts
{
  "layout": "circular",
  "spacing": 1,
  "tracks": [
    {
      "data": {
        "type": "json",
        "chromosomeField": "c",
        "genomicFields": ["p"],
        "values": [{"c": "chr2", "p": 0}]
      },
      "mark": "rect",
      "x": {"field": "p", "type": "genomic"},
      "color": {"value": "lightgray"},
      "opacity": {"value": 0.5}
    }
  ]
}
```

It looks like this happens only for JSON-based tracks.

cc @etowahadams

**Comment by sehilyi** [comment]
I can see a similar error for `#processedTileInfo`:

> Uncaught (in promise) TypeError: Cannot read private member #processedTileInfo from an object whose class did not declare it
    at GoslingTrackClass.drawTile (gosling-track.ts:329:35)
    at GoslingTrackClass.initTile (gosling-track.ts:314:18)
    at GoslingTrackClass.addMissingGraphics (hglib.js:50771:16)
    at GoslingTrackClass.synchronizeTilesAndGraphics (hglib.js:50782:12)
    at GoslingTrackClass.receivedTiles (hglib.js:50833:12)
    at GoslingTrackClass.receivedTiles (gosling-track.ts:728:19)
    at json-data-fetcher.ts:137:17
